module.exports = [
    {
        "url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/8",
        "labels_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/8/labels{/name}",
        "comments_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/8/comments",
        "events_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/8/events",
        "html_url": "https://github.com/rhyolight/sprinter.js/issues/8",
        "id": 37022875,
        "number": 8,
        "title": "Add ability to update milestones across repos by milestone name",
        "user": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "url": "https://api.github.com/repos/rhyolight/sprinter.js/labels/enhancement",
                "name": "enhancement",
                "color": "84b6eb"
            }
        ],
        "state": "open",
        "assignee": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "milestone": {
            "url": "https://api.github.com/repos/rhyolight/sprinter.js/milestones/12",
            "labels_url": "https://api.github.com/repos/rhyolight/sprinter.js/milestones/12/labels",
            "id": 683804,
            "number": 12,
            "title": "Sprint 25",
            "description": null,
            "creator": {
                "login": "rhyolight",
                "id": 15566,
                "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
                "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
                "url": "https://api.github.com/users/rhyolight",
                "html_url": "https://github.com/rhyolight",
                "followers_url": "https://api.github.com/users/rhyolight/followers",
                "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
                "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
                "organizations_url": "https://api.github.com/users/rhyolight/orgs",
                "repos_url": "https://api.github.com/users/rhyolight/repos",
                "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rhyolight/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 1,
            "closed_issues": 1,
            "state": "open",
            "created_at": "2014-06-06T22:30:22Z",
            "updated_at": "2014-07-02T20:48:37Z",
            "due_on": "2014-07-05T07:00:00Z"
        },
        "comments": 0,
        "created_at": "2014-07-02T20:48:37Z",
        "updated_at": "2014-07-02T20:48:37Z",
        "closed_at": null,
        "body": "The syntax should be the same as the `createMilestones` function:\r\n\r\n```\r\nsprinter.updateMilestones('Sprint 20', {\r\n    title: 'Sprint 21',\r\n    due_on: 'Apr 16, 2014'\r\n}, function(err, milestones) {\r\n    console.log(milestones);\r\n});\r\n```\r\n\r\nThis should not create any new Milestones, but should update any existing Milestones with the title \"Sprint 20\" to be renamed to \"Sprint 21\" and due on \"Apr 16, 2014\". "
    },
    {
        "url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/4",
        "labels_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/4/labels{/name}",
        "comments_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/4/comments",
        "events_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/4/events",
        "html_url": "https://github.com/rhyolight/sprinter.js/issues/4",
        "id": 31363251,
        "number": 4,
        "title": "createMilestones output is unformatted",
        "user": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "url": "https://api.github.com/repos/rhyolight/sprinter.js/labels/enhancement",
                "name": "enhancement",
                "color": "84b6eb"
            }
        ],
        "state": "open",
        "assignee": null,
        "milestone": null,
        "comments": 1,
        "created_at": "2014-04-11T21:18:39Z",
        "updated_at": "2014-05-22T20:02:32Z",
        "closed_at": null,
        "body": "The output of a `createMilestones` command just dumps the created milestone JSON to the screen. It should be better formatted with a summary of how many were created."
    },
    {
        "url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/3",
        "labels_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/3/labels{/name}",
        "comments_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/3/comments",
        "events_url": "https://api.github.com/repos/rhyolight/sprinter.js/issues/3/events",
        "html_url": "https://github.com/rhyolight/sprinter.js/issues/3",
        "id": 30485273,
        "number": 3,
        "title": "Error handling for repos with no issue tracker",
        "user": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "url": "https://api.github.com/repos/rhyolight/sprinter.js/labels/bug",
                "name": "bug",
                "color": "fc2929"
            }
        ],
        "state": "open",
        "assignee": null,
        "milestone": null,
        "comments": 0,
        "created_at": "2014-03-31T04:54:03Z",
        "updated_at": "2014-05-22T20:02:42Z",
        "closed_at": null,
        "body": "Displays a nasty error message if one of the repos doesn't have an issue tracker. Boil this down to something nicer and well-formatted. "
    }
];
